### ISSUE TITLE
compile error in src2srcml.cpp regarding urisprefix

### ISSUE THREAD

**Issue by mma66mma** [lashgar/ipmacc#4]
Hello 

i get the following error, when compiling:

vn: E155007: »/home/mma/downloads/ipmacc-master/srcML/src« ist keine Arbeitskopie
src2srcml.cpp: In function ‘int main(int, char**)’:
**src2srcml.cpp:489:28: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
       if (urisprefix[i] == '\0') {**
                            ^~~~
make: *** [Makefile:233: ../obj/src2srcml.o] Fehler 1
. done
~ compiling OpenACC API .openacc.c:233:10: fatal error: cuda.h: Datei oder Verzeichnis nicht gefunden
 #include <cuda.h>
          ^~~~~~~~
compilation terminated.
make: *** [Makefile:34: openacc.o] Fehler 1
. done

i am using gcc 7.3.1

**Comment by lashgar** [comment]
src2srcml is an ancient code that I dropped from a vendor (that is no longer supporting it). Please try adding the following line somewhere early in src2srcml.cpp and recompile:

`#pragma GCC diagnostic ignored "-fpermissive"`

**Comment by mma66mma** [comment]
Hello

it seems gcc ignores the -fpermissive option:

~ compiling srcML parser .svn: E155007: »/home/mma/downloads/ipmacc-master/srcML/src« ist keine Arbeitskopie
svn: E155007: »/home/mma/downloads/ipmacc-master/srcML/src« ist keine Arbeitskopie
src2srcml.cpp:25:32: warning: ‘-fpermissive’ is not an option that controls warnings [-Wpragmas]
 #pragma GCC diagnostic ignored "-fpermissive"
                                ^~~~~~~~~~~~~~
src2srcml.cpp: In function ‘int main(int, char**)’:
src2srcml.cpp:491:28: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
       if (urisprefix[i] == '\0') {
                            ^~~~
make: *** [Makefile:233: ../obj/src2srcml.o] Fehler 1
. done
~ compiling OpenACC API .openacc.c: In function ‘acc_profiler_dump’:
openacc.c:2218:12: warning: implicit declaration of function ‘time’; did you mean ‘utimes’? [-Wimplicit-function-declaration]
     srand (time(NULL));
            ^~~~
            utimes
. done

-- 

mit freundlichen Grüßen / with best regards

Michael Mattes

Am Montag, 22. April 2019, 21:00:43 CEST schrieb Ahmad Lashgar:

**Comment by mma66mma** [comment]
I now changed to problematic line 
from
491       if (urisprefix[i] == '\0') {
to
491       if (urisprefix[i] == NULL) {
and get to and end with the compiling.
But wenn i test a testcase i get:

 ipmacc vectorAdd.c -o vectorAdd 

  warning: storing the translated code in <vectorAdd_ipmacc.cu> (target: <nvcuda>)
Traceback (most recent call last):
  File "/home/mma/downloads/ipmacc-master//codegen.py", line 7211, in <module>
    k.var_kernel_parentsFind()
  File "/home/mma/downloads/ipmacc-master//codegen.py", line 4149, in var_kernel_parentsFind
    self.var_findFuncParents("kernel")
  File "/home/mma/downloads/ipmacc-master//codegen.py", line 4216, in var_findFuncParents
    [template,fname]=srcml_get_parent_fcn(root,kn.strip())
  File "/home/mma/downloads/ipmacc-master/src/..//srcML/wrapper/wrapper.py", line 1309, in srcml_get_parent_fcn
    return srcml_sample.getFunctionParernt(root, func)
  File "/home/mma/downloads/ipmacc-master/src/..//srcML/wrapper/wrapper.py", line 805, in getFunctionParernt
    return [template,'']
UnboundLocalError: local variable 'template' referenced before assignment

is my python to new? i have 2.7.14

**Comment by lashgar** [comment]
My guess is srcml is not able to generate XML AST of the code. Have to reproduce and debug this. Would you mind please specify your OS and libxml (lxml) version?

**Comment by lashgar** [comment]
I integrated compatible version of libxml and libxslt in the package. This issue should be fixed as of https://github.com/lashgar/ipmacc/commit/95512602e548d8ff5b5e9c39013a488f30fc1345

Please update to the tip and retry.
